[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "cb8797b3b32b806d48d8ab644f67a650713c45fc"
os = "macos"

    [[SCOTCH.download]]
    sha256 = "dc62147296dbd8e662dfdee0a5ccea9f34e7d29a784d4bc9b6e222f2ead8f021"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+1/SCOTCH.v7.0.3.aarch64-apple-darwin.tar.gz"
[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "0585d1293af11a6d2905ef6d9b2810aa9d251895"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "a1adf7d389be0fb07c29f13ed90dedb1757e8602c9085c737bf59cb9052ab8dc"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+1/SCOTCH.v7.0.3.aarch64-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "c48b28930679bacd5c5cf871fe2e8d98d4767e6e"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "f3ca47d7e1a18d43096a54b7dccb0324313e79ea4c6c3ef70c6f3b8deab07829"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+1/SCOTCH.v7.0.3.aarch64-linux-musl.tar.gz"
[[SCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8aed563b39badd3a55c41d595dc1ec9b136fbc1c"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "0af9e2f90b8cc5e6e9179d0680c86d310a1d2a4fa86b04f561cc429bd11a3e93"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+1/SCOTCH.v7.0.3.armv6l-linux-gnueabihf.tar.gz"
[[SCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b2142d8207c7f8ca49ddcc04148029315d5fd503"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "de17297d277ebda7b2c09b2f3c2e8f19daebc1abfb59c76c303b3e6425703b09"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+1/SCOTCH.v7.0.3.armv6l-linux-musleabihf.tar.gz"
[[SCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "14711ffabcdc9e11cb4ea7346d95c92383c7cf8d"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "00c91bef7f5deb3325f8c6ab183ec496efd59f7fc7a1dff487d328e1af72cdd8"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+1/SCOTCH.v7.0.3.armv7l-linux-gnueabihf.tar.gz"
[[SCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f7726bbb7f57923099c386873feb099f8d6e88ed"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "0c16c0b1b7bdd6abcacb47cf2c4fcaa0d0a659cb7b8d6d866b4c805aa6a9e2d2"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+1/SCOTCH.v7.0.3.armv7l-linux-musleabihf.tar.gz"
[[SCOTCH]]
arch = "i686"
git-tree-sha1 = "a99048f53803a8736e4946beb814f19ab2717a5c"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "34910cb53768ce71c4e9fea28175dc3eb8373d4942f771e37593f01b852902cf"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+1/SCOTCH.v7.0.3.i686-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "i686"
git-tree-sha1 = "231e2580a3101fb66b39ebccadc36af19488615d"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "f383f5db6612cb917904e7e78383e942ac2de72a2b4c1ebc5021fd206f541227"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+1/SCOTCH.v7.0.3.i686-linux-musl.tar.gz"
[[SCOTCH]]
arch = "i686"
git-tree-sha1 = "cf3a9a41d2fa502061155f6a2f55316f42b87534"
os = "windows"

    [[SCOTCH.download]]
    sha256 = "ce5d10b954e697029e8fd376ea7c4eda26e5afb3cf5b683996b246c19f755b92"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+1/SCOTCH.v7.0.3.i686-w64-mingw32.tar.gz"
[[SCOTCH]]
arch = "powerpc64le"
git-tree-sha1 = "987d98aac52cd740299a655dcc98abbb4c965c18"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "8473d989ca0f654a47cfe23909152bfda1147f95375405c521e41283e6d37499"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+1/SCOTCH.v7.0.3.powerpc64le-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "632d91c8a1828973c537d0c955f2ad72bf810006"
os = "macos"

    [[SCOTCH.download]]
    sha256 = "bc8411292d228a0c4751ed2dc2d109e21f4efd6c048a4fcdbcf5cfe24033e14a"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+1/SCOTCH.v7.0.3.x86_64-apple-darwin.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "428b857be4c6405f829cdc4764db203134334b84"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "e2d12d96753f5f383ffb71b57f3520aae41b2cefb50cff8ed82c34aec2684d50"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+1/SCOTCH.v7.0.3.x86_64-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "7d658c1a49252b6de5ce526164c8f803a85ca4da"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "fc7a4302e1e84262209ac2c680af7f422ff2708177f8d126bbbaf98428fb69d8"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+1/SCOTCH.v7.0.3.x86_64-linux-musl.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "208de086c0d8b6670a87faa130e6057d7ee255e3"
os = "windows"

    [[SCOTCH.download]]
    sha256 = "e6a291bcadc838156b67f1f38eeb804585bdfd0b6e03b90015910b3587a6275c"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+1/SCOTCH.v7.0.3.x86_64-w64-mingw32.tar.gz"
