[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "bd4c83c32c5e5d9e4510223f724cf7febc51f124"
os = "macos"

    [[SCOTCH.download]]
    sha256 = "7ec118dce2e50814a94fbb1bc1f73a59d1f04a2a13a7bb0764e955faa7fc0ef0"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+0/SCOTCH.v7.0.3.aarch64-apple-darwin.tar.gz"
[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "cae0ee9540b898ba997b6a4ac59e5406565cd5c4"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "7a607bfb2d95738afcfca3a0af3463609f24fcd4158bd08a4b6f5135c3903d47"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+0/SCOTCH.v7.0.3.aarch64-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "d7b8e8741011b6ef07920796f2d32e1ee5c6413d"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "9603157283b03f7731a7480944f58454d99efe7b87945f4c960c75fd8f10cb07"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+0/SCOTCH.v7.0.3.aarch64-linux-musl.tar.gz"
[[SCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d07a6b31aa783459bbb498ce6a9245d3932aea1c"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "5b270b9ce1feecb57f95c63f797eb9aeb9edc29a07e207a8876cbc5865110812"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+0/SCOTCH.v7.0.3.armv6l-linux-gnueabihf.tar.gz"
[[SCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "176fc38f85e8e7a806b3d8beb558be5bfa54adf4"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "f7c13cd6f1c0c968688b3d86c8e8470f5d143e74056d91e89c371f84a1cdc774"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+0/SCOTCH.v7.0.3.armv6l-linux-musleabihf.tar.gz"
[[SCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a9290a8e82f308aa3cbf5b9155cc9a898d85cd99"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "d56005119ed9ef7c745d10868fbd1201ef3532d742c6997a3866167ca6e6fc9b"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+0/SCOTCH.v7.0.3.armv7l-linux-gnueabihf.tar.gz"
[[SCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "79c760db3809acc5a4be3404ccc6529a25c83a74"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "a2d6daa7ced7a53c78388b62cb9495ccedd5f29d79575ab316b00ba62f0122fc"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+0/SCOTCH.v7.0.3.armv7l-linux-musleabihf.tar.gz"
[[SCOTCH]]
arch = "i686"
git-tree-sha1 = "39e8df18460562800d1e0843c36941b99b3d5441"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "df0a47835c118cf1f9b6198a411f88efdfb5c1dce2014b187f21f1247cbfcb67"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+0/SCOTCH.v7.0.3.i686-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "i686"
git-tree-sha1 = "cfcec6b12f69c8ff528ede4b25ebfed21aa1cbe0"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "29d0f86851761caa3456168433d5d7c306f5973a713c3d3674925dbe512f9317"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+0/SCOTCH.v7.0.3.i686-linux-musl.tar.gz"
[[SCOTCH]]
arch = "i686"
git-tree-sha1 = "c55cb15f90aaba5c4ec1f527cad739e67b9b2c6a"
os = "windows"

    [[SCOTCH.download]]
    sha256 = "bf00328a2631b7234fb1e01ad6d24b9a8cfdf6e3d0d8f73a14fe8762f812cf3b"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+0/SCOTCH.v7.0.3.i686-w64-mingw32.tar.gz"
[[SCOTCH]]
arch = "powerpc64le"
git-tree-sha1 = "71ffdb58423c4e0495919b5bef7c90963ca0ff4d"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "ca75e4652a0dd47e2952d9190fd1efff1c4f856ef82e2ee10b960811428e78c5"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+0/SCOTCH.v7.0.3.powerpc64le-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "0522fd8bae24041a33c9a398df634836e507b713"
os = "macos"

    [[SCOTCH.download]]
    sha256 = "f5c8ae6585b728eab4232dffe1e31dc7f9748fbfb5ab775b86e8794864e7fbdc"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+0/SCOTCH.v7.0.3.x86_64-apple-darwin.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "2b5998b0295e279dfbbd714eaa552c41fc405ab3"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "ba6f97cf1ee184ee7491a66631d92db8a240e2428a52264d4c3a97c26f5df7c7"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+0/SCOTCH.v7.0.3.x86_64-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "d5efc23b4a651ab1c5e6ee28b926eaf5dc580817"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "b9be6695876f97fdee9c3d02d7d0f6540eebaef9f0f8a0fd1004698da2db88d7"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+0/SCOTCH.v7.0.3.x86_64-linux-musl.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "610cbe51d9612659ac8123c54984b44c5b0e0c67"
os = "windows"

    [[SCOTCH.download]]
    sha256 = "fbd505fb74f187a0769a990e8f46bf189ca409e16732d7d5196f1d0c091ca79a"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.3+0/SCOTCH.v7.0.3.x86_64-w64-mingw32.tar.gz"
