[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "8f841748b2e3e0acd473fd8a604ce3cfdc1567ab"
os = "macos"

    [[SCOTCH.download]]
    sha256 = "97e86c0799bb214bf0e77ed37babffd310ef948dc2cff105428c29256bb49e73"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+1/SCOTCH.v7.0.6.aarch64-apple-darwin.tar.gz"
[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "77b7d30215bae1ba0dc77a95fb8659ac59d7a4ef"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "eb1f9184505f064aad8ec8aea0e3b539f099c1b011e45b7e46eb3ac27b7f2258"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+1/SCOTCH.v7.0.6.aarch64-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "e05b55c8d3021aa71474a2168d073445738e0424"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "7dd4bc8e1d28956781408cd8c8bbb8b1258687abd9f28bcb470511b2c47174b2"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+1/SCOTCH.v7.0.6.aarch64-linux-musl.tar.gz"
[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "d4fa027e964e4cde68fd5543db73087ed59a09c0"
os = "freebsd"

    [[SCOTCH.download]]
    sha256 = "f35fc5ac2e546125f83b30213ad10b74e6a6f4dacb008e3a468cda94c4a08130"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+1/SCOTCH.v7.0.6.aarch64-unknown-freebsd.tar.gz"
[[SCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bba26bcc1697298f434fde8f5ac96504d75b20dd"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "d1d619f02e8403520b88ed0ab5a5b650e3a02500d1fc5ec0d638ed1e5adf3e37"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+1/SCOTCH.v7.0.6.armv6l-linux-gnueabihf.tar.gz"
[[SCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "76aacb324e4a83398bcda4e6a8f74adabcb73149"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "07454b9388da672b7094625f1af935c803ff0d99f0f224262c23be9e6b3e51b4"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+1/SCOTCH.v7.0.6.armv6l-linux-musleabihf.tar.gz"
[[SCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ad6d03b0e181b36e707a595be0c00a39cf26e0b5"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "3087bf1ea0954b828b1d60cfab57e9c1fd86465f7af2357e1cbd9f9b4726e5f4"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+1/SCOTCH.v7.0.6.armv7l-linux-gnueabihf.tar.gz"
[[SCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cf524b5f5a051647b708b945ea51d1208d10d74c"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "7001f204f0829460fb11d365ebbb5bef963c9b54696281ecdc1852ad0e4bc173"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+1/SCOTCH.v7.0.6.armv7l-linux-musleabihf.tar.gz"
[[SCOTCH]]
arch = "i686"
git-tree-sha1 = "a13e5bb28b6ba33847d8ab4a6d0e34c996a185d2"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "e3ac4593c38d52b59fd2313f3fabc449411b79f667a76ca4641903294878a7d9"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+1/SCOTCH.v7.0.6.i686-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "i686"
git-tree-sha1 = "8de19dd13afb7f2ea872f1b884d48d05daf89100"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "0fe2ccccd5e173c1ab9c1f7aa0333f402c31e57517810e6d9c0bdb4e0d318c34"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+1/SCOTCH.v7.0.6.i686-linux-musl.tar.gz"
[[SCOTCH]]
arch = "i686"
git-tree-sha1 = "09b3da949aaf842f3b9904a93f91772e8bd656af"
os = "windows"

    [[SCOTCH.download]]
    sha256 = "c2008c2d80e60683965a335c34fa0f8ecadb9c3e4c3e2d16538202359a7f2b7e"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+1/SCOTCH.v7.0.6.i686-w64-mingw32.tar.gz"
[[SCOTCH]]
arch = "powerpc64le"
git-tree-sha1 = "f6e4f68198b017fbd358093cca5e57e4d9811763"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "b3b39a9d5a9e5df8775e4e84b67c55161baf6179b63774c886816ddc5afb3032"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+1/SCOTCH.v7.0.6.powerpc64le-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "52f60bed876c4f8b6c85822029bfadd4750873c1"
os = "macos"

    [[SCOTCH.download]]
    sha256 = "70aa0130b4fc298d0593b65c2945f321be6066c174a9f8336a68af82319687d5"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+1/SCOTCH.v7.0.6.x86_64-apple-darwin.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "dee4cf51795976ee3232b834fec63ffeefe4a5a4"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "eebc908e36ec607bfa484c0e85d390fb1a12362108c082014b4cf565bf287202"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+1/SCOTCH.v7.0.6.x86_64-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "a0d6abba27a53a0417e7892e7861defbccc166a1"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "4a671530708bf24b2cf34b516c0e8b9bce67e8bfa9e450aa0f99cb7eb969573f"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+1/SCOTCH.v7.0.6.x86_64-linux-musl.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "796df73a0a605c81c591ae38398ae1c9973864e0"
os = "freebsd"

    [[SCOTCH.download]]
    sha256 = "9ea18a4c7c4755e35a1bc1c47df837b84e91c1517ed288943c5aed7289ebdcd6"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+1/SCOTCH.v7.0.6.x86_64-unknown-freebsd.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "707f0d84f93a751e8cfafa9e5e5f5025cb5b5e97"
os = "windows"

    [[SCOTCH.download]]
    sha256 = "a35e2dea0b007b1d9f3f19bcd2a05b829d44d34bacbdc8cd43ce78e797bea4de"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+1/SCOTCH.v7.0.6.x86_64-w64-mingw32.tar.gz"
