[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "c560fb1585b093a8b6fbaf89c3b44c35b5f7e3f8"
os = "macos"

    [[SCOTCH.download]]
    sha256 = "51342051466ad7393009b2dae903e7d27e480c929de8a7d619a7710978262b6d"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v6.1.3+0/SCOTCH.v6.1.3.aarch64-apple-darwin.tar.gz"
[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "f8e75d7426bdf70918aeafc94f531d4a435c0135"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "8ebea3bc6aa5e3b13a3672c735dff7c29c6faa1223a1e7e46ba5d84273cbe2b0"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v6.1.3+0/SCOTCH.v6.1.3.aarch64-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "d408c51d7b9c12ad0477c2935068d60c1d986805"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "2118cd75f5b32bbd7ce6f7567bb967d0149c3194ad61734aa7cd9eb9b6fbbf2a"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v6.1.3+0/SCOTCH.v6.1.3.aarch64-linux-musl.tar.gz"
[[SCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "249c37a93f4a1e1120c44519a271a3a339af89da"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "e5ab61c36ab82a425f63c91003c3aa3d2b3fab8a855455618c7e0b7a73085de6"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v6.1.3+0/SCOTCH.v6.1.3.armv6l-linux-gnueabihf.tar.gz"
[[SCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7a2f4deca8d4a8564d8cad170c4f912baa8772d5"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "f4467f93598a1bb818d75b7ab00d15ffa00aa76ee57926907be2cd9f5e4dd404"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v6.1.3+0/SCOTCH.v6.1.3.armv6l-linux-musleabihf.tar.gz"
[[SCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fcbb7b2a79ca0e619d7c346d53350789aa4f28d7"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "49bea79f396e05b5bca454a393e3e07dc4a4cd98f78d62c2829f22d80e2fade3"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v6.1.3+0/SCOTCH.v6.1.3.armv7l-linux-gnueabihf.tar.gz"
[[SCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "50273564368852eea73143c327b2b64bb254e120"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "16e2b86e3d8b9b2f53204048e7f5364422256913990d8be3c82271ee78052307"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v6.1.3+0/SCOTCH.v6.1.3.armv7l-linux-musleabihf.tar.gz"
[[SCOTCH]]
arch = "i686"
git-tree-sha1 = "0f43607cc012259c5075fa08bdbe690c1a55e391"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "3b553235e503c7668d35fc9995dc75f84c8b99ad7e88eaae0837985fc65f0b32"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v6.1.3+0/SCOTCH.v6.1.3.i686-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "i686"
git-tree-sha1 = "bf8e48490b745cfcc119671ad2748ff3453239dc"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "52daddba33770bbdfff75bc36d66ca1b8b7731b0a01be9db547530d430700ea5"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v6.1.3+0/SCOTCH.v6.1.3.i686-linux-musl.tar.gz"
[[SCOTCH]]
arch = "powerpc64le"
git-tree-sha1 = "e09a5d450ea1e4e3286b470331363e0ed15d9157"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "5bebabffb4a1de3143cb35ece93dc9590e6734ee5774f648670a3871902ebfad"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v6.1.3+0/SCOTCH.v6.1.3.powerpc64le-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "7caf09d75e970e2f90fcfad9fde348ea92104485"
os = "macos"

    [[SCOTCH.download]]
    sha256 = "2602cd521c8880e24e9961166ea6740d53492d197192e972481316d91bb7bb7c"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v6.1.3+0/SCOTCH.v6.1.3.x86_64-apple-darwin.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "9b557abbb805e407e085191c2a1ab4bfa763ffae"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "8abbd200fba239199f22f04980f9a05eef5dca3c47ebb398ed7e1132f932dd59"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v6.1.3+0/SCOTCH.v6.1.3.x86_64-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "01dfbb1ad8f81a80d3812e7a86b38785aba6b811"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "f48f09a96097cbc0f4d5ee0a26917ee5fe46ae9dbb981fd074b99f284dd89d2d"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v6.1.3+0/SCOTCH.v6.1.3.x86_64-linux-musl.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "593f3d917c83a72baa0c944f6bf407ecc60faa71"
os = "freebsd"

    [[SCOTCH.download]]
    sha256 = "d502d3d357074d1b8d2a07cd666bc07e51e7d39b087428deee9f8856cb361b28"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v6.1.3+0/SCOTCH.v6.1.3.x86_64-unknown-freebsd.tar.gz"
