[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "31baa41c0c660def9e0abd5a9c8daafc5662b800"
os = "macos"

    [[SCOTCH.download]]
    sha256 = "ca0389d7ab25f680e1f79267995b44e73374c34e908ab5b8b19486025f569e9a"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.7+0/SCOTCH.v7.0.7.aarch64-apple-darwin.tar.gz"
[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "6239fe97c2301e54ec6ae14517572134e2c25d0b"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "2f25b7e4ef5322265d574b95e50c237a655f68a6b2782d04f516d43480078734"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.7+0/SCOTCH.v7.0.7.aarch64-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "9a58603c2e7fad1acfa1c6985270081effe85906"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "9528361955a8223f433972c3b9caf1138a822b3d34c396746640d62e58c0cfe3"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.7+0/SCOTCH.v7.0.7.aarch64-linux-musl.tar.gz"
[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "b2d8772bdf6b4471fbcc9a3420269f2a47eeea6a"
os = "freebsd"

    [[SCOTCH.download]]
    sha256 = "7dc76a7a5d555dafd3767577447873ef042b11051fa2a8ca97057abaa510d6db"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.7+0/SCOTCH.v7.0.7.aarch64-unknown-freebsd.tar.gz"
[[SCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4e318744a517b8166234c4feb5a1daf7b6ee41e5"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "fbe4ef3e8c3df0909810ebb39e6f81700f2d32ac99bcd8b754595e78d80920b2"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.7+0/SCOTCH.v7.0.7.armv6l-linux-gnueabihf.tar.gz"
[[SCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6bc0fb6e79670d5b8d8f3536e41bae7ae26627b9"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "c309c9e47a95f1de044660700fa01c6689976662e0f0ce50c29543bb4a71d9a6"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.7+0/SCOTCH.v7.0.7.armv6l-linux-musleabihf.tar.gz"
[[SCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "203082038d05cef4a3b4c8dd727c2bc4f67505bd"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "42245424b44aeeacf6e166454be904e58aa18b881aac9af5b041c4e6da458fd2"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.7+0/SCOTCH.v7.0.7.armv7l-linux-gnueabihf.tar.gz"
[[SCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2c9282d0f143eb0284220760c6fbf86e9f29b99d"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "791ca3fad7bcc2c129a010701c213d569f8481c620336080f7e20e9fd39d5451"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.7+0/SCOTCH.v7.0.7.armv7l-linux-musleabihf.tar.gz"
[[SCOTCH]]
arch = "i686"
git-tree-sha1 = "be5d629e5b94555c34452084f20f26898a130743"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "f5008b457c8caa1aa13405711e37eaffbc8560ef06aa3a834cc1c9477a6dd81d"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.7+0/SCOTCH.v7.0.7.i686-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "i686"
git-tree-sha1 = "913de9e6ad8f83908fbf1bb478274b1521e6a406"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "1a63dfe1ec6fc6f7d68321a3c5889fb33662b6711b99a2abd79f9efb7d0567f6"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.7+0/SCOTCH.v7.0.7.i686-linux-musl.tar.gz"
[[SCOTCH]]
arch = "i686"
git-tree-sha1 = "7bc87a67e81c42c8c52d049a94f5ac8b30cf413b"
os = "windows"

    [[SCOTCH.download]]
    sha256 = "bbc1bc490159cf763819b72f242cd5a74b04e6ff7f1bcfb9e4cf587b75cde051"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.7+0/SCOTCH.v7.0.7.i686-w64-mingw32.tar.gz"
[[SCOTCH]]
arch = "powerpc64le"
git-tree-sha1 = "dc9a9eed5886944fb06fec13b5765c1a987a3af0"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "cd87030ce4fa6193a9a5f302e5a679b7897a3a38d2091951c31413bd90a1e628"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.7+0/SCOTCH.v7.0.7.powerpc64le-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "riscv64"
git-tree-sha1 = "4d21becd41716f8c27cbe0ae57248fb24805427e"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "fc10c296016c5925005862eedb074777eca076a33f911d5376f626e277ab46e6"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.7+0/SCOTCH.v7.0.7.riscv64-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "8b874f669ccaf98f2e2b4a439f09e618c4cc0d34"
os = "macos"

    [[SCOTCH.download]]
    sha256 = "3370351c37ad8ff517a7302bf87c498f6c8db8381c21b8fd72a961546d88c777"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.7+0/SCOTCH.v7.0.7.x86_64-apple-darwin.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "f748676dc7b1eb87871ca052ded5e0a82aa5f8e1"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "f2c7e620f4987796eb2ed55cd5853effc25f0de1ac94ff3f4f6808b1b30dcf57"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.7+0/SCOTCH.v7.0.7.x86_64-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "6823bcc1103fded273319324d93f6aed895de0c7"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "6519fd5f23bd99855a9e78ebced7867123fab905492efa1c74bc3afce9344c1c"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.7+0/SCOTCH.v7.0.7.x86_64-linux-musl.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "6a33ce1aefbfe1631fb4ac1741a2412adbeafa5a"
os = "freebsd"

    [[SCOTCH.download]]
    sha256 = "c40ad5ec003e192edb5d931e9e1fd5b5143f9e03a0088d24e6e2c12f1fa8056b"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.7+0/SCOTCH.v7.0.7.x86_64-unknown-freebsd.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "c3574a08dd48c604650ec2ef92ee7e36b73a1454"
os = "windows"

    [[SCOTCH.download]]
    sha256 = "f593fc860f12d75f67b345c0fe52b716d01d43e10b0cb24af5ba6153a0097d54"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.7+0/SCOTCH.v7.0.7.x86_64-w64-mingw32.tar.gz"
