[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "f934467d4a7d6fd22ccd9c710803997124001cdb"
os = "macos"

    [[SCOTCH.download]]
    sha256 = "13287ae537deabb7f45e8545ae8a99ebeb5abb127131a7f674ac55ed462588c7"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+0/SCOTCH.v7.0.6.aarch64-apple-darwin.tar.gz"
[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "393c00cb2d1d77e517d3e6b642f81038e3d6e870"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "039b278822208a03796a1c40684c4b7442b5ae5c1b0369063a0715abaca88f82"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+0/SCOTCH.v7.0.6.aarch64-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "ddb7d7c0e52d1abe1945cff82c57f09963570db1"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "fcfd65aec0f00db3e3f098eeb5405caca5546db7cab440d239272720f8f75175"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+0/SCOTCH.v7.0.6.aarch64-linux-musl.tar.gz"
[[SCOTCH]]
arch = "aarch64"
git-tree-sha1 = "d9881c73cefb97f105611d96c45cc0631ee47862"
os = "freebsd"

    [[SCOTCH.download]]
    sha256 = "505e9ee3cb70627ab6f6864337462a921441f7beb7ead0da5e4984722d1e3ade"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+0/SCOTCH.v7.0.6.aarch64-unknown-freebsd.tar.gz"
[[SCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2dbe58d7b2ca0297dfb25f7e28935cff97cc63aa"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "76c78ae831e1c13e2e008e45109a1a76e2da4b9a0cb7caa5b73013b8a4e13e96"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+0/SCOTCH.v7.0.6.armv6l-linux-gnueabihf.tar.gz"
[[SCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bc5a1b9dec072c16bc0d85e1c445724fd28c4f6b"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "2103c195637c33e508ee09724acc7f0a0e0a5d1109dff5218997e4d3792fc993"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+0/SCOTCH.v7.0.6.armv6l-linux-musleabihf.tar.gz"
[[SCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c3ccefa3986f76e63970e839dea7170f2c25094b"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "c9fd1d5fef2651078d899f288d9bb6d9c4895dabc078c796c3ca7e9a34744e50"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+0/SCOTCH.v7.0.6.armv7l-linux-gnueabihf.tar.gz"
[[SCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d6e74886b74a22b8003f9e2ce463518562bcf597"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "fd68c1be77b60b134422c1237b811ca9761e431e02140f7f43a4961229ea3e24"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+0/SCOTCH.v7.0.6.armv7l-linux-musleabihf.tar.gz"
[[SCOTCH]]
arch = "i686"
git-tree-sha1 = "6d2a97b3e05625a8e169d6219b7fe3d1b8a31a14"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "86c81ffd3b37b788c9f65ae5659a982d60a0a76d74aafa89a26acaa73d1a674f"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+0/SCOTCH.v7.0.6.i686-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "i686"
git-tree-sha1 = "52e9e29824b872f8c6721478765c7cb0f20e3a56"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "4d2b05e04bd08e7b467a4cf8e3b97b54b1aa618727b18ed5ce4b2e011e68c641"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+0/SCOTCH.v7.0.6.i686-linux-musl.tar.gz"
[[SCOTCH]]
arch = "i686"
git-tree-sha1 = "5aac588c6787bd8d51c04b5e7077475d4efe56fc"
os = "windows"

    [[SCOTCH.download]]
    sha256 = "843e8dab5d4f2467ebb619f31bafe1085b001b0032078207bc6a28ba0c6f5009"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+0/SCOTCH.v7.0.6.i686-w64-mingw32.tar.gz"
[[SCOTCH]]
arch = "powerpc64le"
git-tree-sha1 = "11d1b20becbd2c3eaf9d80e909073d22982ba74c"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "372eaea9b066ccc44e57415f720a273f51563d94040907a2c106301c7b559a4a"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+0/SCOTCH.v7.0.6.powerpc64le-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "e7c0ebead3efa08c9975793b5f08742fb15b22a6"
os = "macos"

    [[SCOTCH.download]]
    sha256 = "922521029b1939d1bbed052caae3eec4989282a47028d928157dde0b6a30c55b"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+0/SCOTCH.v7.0.6.x86_64-apple-darwin.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "db79ef8f1a00e1fcb35a0092931ba5cc582f04e7"
libc = "glibc"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "35fea796a98f75be9730a2b190d758beeb7dcce73552e156fbb70d7a7309ed97"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+0/SCOTCH.v7.0.6.x86_64-linux-gnu.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "78de14299e34f19808ebdb8f44a2ad9bffa71218"
libc = "musl"
os = "linux"

    [[SCOTCH.download]]
    sha256 = "e5a13b7f3787aeadf43729187c79cfd94a943ba1c208aaeb7b7430db22fa1a6f"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+0/SCOTCH.v7.0.6.x86_64-linux-musl.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "136b4dd4debaab41f10d8fcda2de9aa7f45b64d3"
os = "freebsd"

    [[SCOTCH.download]]
    sha256 = "844c4d75fafd918b341fb716691e179f253156c1a52736734f8e68de23f59d92"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+0/SCOTCH.v7.0.6.x86_64-unknown-freebsd.tar.gz"
[[SCOTCH]]
arch = "x86_64"
git-tree-sha1 = "69bbd21b06195bd0de66ba47024beeffd0dc2001"
os = "windows"

    [[SCOTCH.download]]
    sha256 = "2ac08ac9f158549b74bf160382d0b73bd8b750fa1ca6333b8e41360a578289c0"
    url = "https://github.com/JuliaBinaryWrappers/SCOTCH_jll.jl/releases/download/SCOTCH-v7.0.6+0/SCOTCH.v7.0.6.x86_64-w64-mingw32.tar.gz"
