# Autogenerated wrapper script for SCOTCH_jll for aarch64-apple-darwin
export libesmumps, libscotch, libscotcherr, libscotcherrexit, libscotchmetis

using Zlib_jll
JLLWrappers.@generate_wrapper_header("SCOTCH")
JLLWrappers.@declare_library_product(libesmumps, "@rpath/libesmumps.dylib")
JLLWrappers.@declare_library_product(libscotch, "@rpath/libscotch.dylib")
JLLWrappers.@declare_library_product(libscotcherr, "@rpath/libscotcherr.dylib")
JLLWrappers.@declare_library_product(libscotcherrexit, "@rpath/libscotcherrexit.dylib")
JLLWrappers.@declare_library_product(libscotchmetis, "@rpath/libscotchmetis.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        libesmumps,
        "lib/libesmumps.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libscotch,
        "lib/libscotch.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libscotcherr,
        "lib/libscotcherr.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libscotcherrexit,
        "lib/libscotcherrexit.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libscotchmetis,
        "lib/libscotchmetis.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
