# Autogenerated wrapper script for SCOTCH_jll for i686-w64-mingw32
export libesmumps, libscotch, libscotcherr, libscotcherrexit, libscotchmetisv3, libscotchmetisv5

using CompilerSupportLibraries_jll
using Zlib_jll
using Bzip2_jll
using XZ_jll
JLLWrappers.@generate_wrapper_header("SCOTCH")
JLLWrappers.@declare_library_product(libesmumps, "libesmumps.dll")
JLLWrappers.@declare_library_product(libscotch, "libscotch.dll")
JLLWrappers.@declare_library_product(libscotcherr, "libscotcherr.dll")
JLLWrappers.@declare_library_product(libscotcherrexit, "libscotcherrexit.dll")
JLLWrappers.@declare_library_product(libscotchmetisv3, "libscotchmetisv3.dll")
JLLWrappers.@declare_library_product(libscotchmetisv5, "libscotchmetisv5.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Zlib_jll, Bzip2_jll, XZ_jll)
    JLLWrappers.@init_library_product(
        libesmumps,
        "bin\\libesmumps.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libscotch,
        "bin\\libscotch.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libscotcherr,
        "bin\\libscotcherr.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libscotcherrexit,
        "bin\\libscotcherrexit.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libscotchmetisv3,
        "bin\\libscotchmetisv3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libscotchmetisv5,
        "bin\\libscotchmetisv5.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
